---
title: "Project 02"
author: "Zoe Chow", "Chris Fitzgerald", "Little Butler"
date: "`r Sys.Date()`"
output:
    github_document:
        toc: true
        toc_depth: 2
        html_preview: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library('reticulate')
use_python('/usr/bin/python3')
```

# Markov Chains

------------------------------------------------------------------------

In class today we will be implementing a Markov chain to process sentences

------------------------------------------------------------------------

## Learning Objectives

1.  Students will be able to explain the Markov Chain process\
2.  Implement a Markov Chain

------------------------------------------------------------------------

## Background

Markov Chains represent a series of events following the Markov Property: future states are memory-less in that they depend only on the current state. This can be expanded to the idea of variable order Markov models where there is a variable-length memory (eg. 1st order Markov Model). Markov models consist of fully observable states.

> A common example of this is in predicting the weather: We can clearly see the current weather and would like to predict tomorrow's weather. This is also applicable to biology with one case being CpG islands.

Our goal today will be to implement a Markov model built from words. For our example text, we will use the classic example of Dr. Seuss because of the repetitive nature of the text.

------------------------------------------------------------------------

## Train Markov model

For our initial implementation of the Markov Model, we will use the simple example of Dr. Seuss: "One fish two fish red fish blue fish."

### Note

create a`list` of unique occurrence of each word in the `string` create an empty `dict` find location of each occurrence of a word from the `list` in the original `string` identify the word after it add the word as a key to the `dict` if it doesn't exist and set its value to `1` otherwise, increase its value by `1`

Identify the first and last word of the `string` add `'*S*'` as a key to the `dict` and the first word of the `string` as a transition occurrence. add `'*E*'` as a transition occurrence from the last word of the `string`

```{python}
def build_markov_model(markov_model, new_text):
    '''
    Function to build or add to a 1st order Markov model given a string of text
    We will store the markov model as a dictionary of dictionaries
    The key in the outer dictionary represents the current state
    and the inner dictionary represents the next state with their contents containing
    the transition probabilities.
    Note: This would be easier to read if we were to build a class representation
    of the model rather than a dictionary of dictionaries, but for simplicitiy
    our implementation will just use this structure.
    
    Args: 
    markov_model (dict of dicts): a dictionary of word:(next_word:frequency pairs)
    new_text (str): a string to build or add to the moarkov_model
    
    Returns:
    markov_model (dict of dicts): an updated markov_model
    
    Pseudocode:
    Add artificial states for start and end
    For each word in text:
    Increment markov_model[word][next_word]
    
    '''
    
    
    key = []  # Initiate list
    words = new_text.split()  # split text string to create list
    
    # loop through text and build unique list
    for word in words:
        if word not in key:
            key.append(word)
    
    # creating key/value for start state
    start = words[0]
    start_dict = {}
    start_dict[start] = 1
    markov_model['*S*'] = start_dict
    
    # Iterate through unique keys and text to find location of each occurrence of the word
    for target in key:
        inner_dict = {}  # initiate inner dictionary
        indices = [index for index, word in enumerate(words) if word == target]  # get all indices of words
        
        # loop through indices and get next word
        for position in indices:
                
            if position != len(words) -1:
                next_word = words[position + 1]
                
                if next_word not in inner_dict:
                    inner_dict[next_word] = 1 
                else:
                    inner_dict[next_word] += 1
            else:
                inner_dict['*E*'] = 1  # add end if last 
            
        markov_model[target] = inner_dict  # combine dictionaries
    
            
                
    return(markov_model)
        
        

markov_model = dict()
text = "one fish two fish red fish blue fish"
markov_model = build_markov_model(markov_model, text)
print(markov_model)
```

Expected output:

```         
{'*S*': {'one': 1}, 'one': {'fish': 1}, 'fish': {'two': 1, 'red': 1, 'blue': 1, '*E*': 1}, 'two': {'fish': 1}, 'red': {'fish': 1}, 'blue': {'fish': 1}}
```

### Nth order Markov chain

In the above model, each event or word is output from only the previous state with no memory of any prior states. While this is useful in some cases, typical biological applications of Markov chains require higher-order models to accurately capture what we know about a system. For instance, in attempting to identify coding regions of a genome, we know that open reading frames (ORFs) contain codon triplets, and so a third or sixth order Markov chain would better describe these regions. Here you will implement a generalized form of our previous Markov Chain to allow for Nth order chains.

### Notes

Use recursion, see Fibonacci order is number of recursion, and the core `else` statement is our original model

```{python}
def build_markov_model(markov_model, text, order=1):
    '''
    Function to build or add to a Nth order Markov model given a string of text
    
    Args: 
    markov_model (dict of dicts): a dictionary of word:(next_word:frequency pairs)
    or None if a new model is being built
    new_text (str): a string to build or add to the moarkov_model
    order (int): the number of previous states to consider for the model
    
    Returns:
    markov_model (dict of dicts): an updated/new markov_model
    '''
    #if type(text) == str:  #removed bc recursion did not loop correctly
    text = text+ " *E*" 
    text = text.split()   

    # add start state to markov_model dictionary
    start = tuple(text[:order])
    start_dict = {}
    start_dict[start] = 1
    markov_model['*S*'] = start_dict

    # iterate through each position of the text, but stop after the last possible combo
    for i in range(len(text) - order):
        current_combo = tuple(text[i:i+order])  
        next_text = text[i+order]  
            
        if current_combo not in markov_model:
            markov_model[current_combo] = {}
        
        if next_text in markov_model[current_combo]:
            markov_model[current_combo][next_text] += 1
        else:
            markov_model[current_combo][next_text] = 1
    return markov_model

markov_model = dict()
text = "one fish two fish red fish blue red fish blue"
markov_model = build_markov_model(markov_model, text, 2)
# build_markov_model(markov_model, text, 2)
print(markov_model)
```
## Generate text from Markov Model

Markov models are "generative models". That is, the probability states in the model can be used to generate output following the conditional probabilities in the model.

We will now generate a sequence of text from the Markov model. For this section, I recommend using np.random.choice, which allows for you to provide a probability distribution for drawing the next edge in the chain.

### Notes

use `current_word` to search our outer key of our dict calculate the probability of each of the possible following words use a random number generator to choose the next word continue until we hit an `*E*`

```{python}
import numpy as np


def get_next_word(current_word, markov_model, seed=42):
    '''
    Function to randomly move a valid next state given a markov model
    and a current state (word)
    
    Args: 
    current_word (tuple): a word that exists in our model
    markov_model (dict of dicts): a dictionary of word:(next_word:frequency pairs)
    
    Returns:
    next_word (str): a randomly selected next word based on transition probabilies
    
    Pseudocode:
    Calculate transition probilities for all next states from a given state (counts/sum)
    Randomly draw from these to generate the next state
    
    '''
    inner_dict = markov_model[current_word]
    total_frequency = sum(inner_dict.values())
    
    for key in inner_dict:
        inner_dict[key] = inner_dict[key]/total_frequency
    
    words = list(inner_dict.keys())
    probabilities = list(inner_dict.values())
    
    next_word = np.random.choice(words, p=probabilities)
    
    return next_word

#print(get_next_word(('fish', 'blue'), markov_model))
```


```{python}
def generate_random_text(markov_model, seed=42):
    '''
    Function to generate text given a markov model
    
    Args: 
    markov_model (dict of dicts): a dictionary of word:(next_word:frequency pairs)
    
    Returns:
    sentence (str): a randomly generated sequence given the model
    
    Pseudocode:
    Initialize sentence at start state
    Until End State:
    append get_next_word(current_word, markov_model)
    Return sentence
    
    '''
    start_state = get_next_word("*S*", markov_model)  # gets first few words
    
    # nth order markov_chain
    if type(start_state) is tuple:
        sentence = " ".join(start_state)  # convert tuple to strings for sentence
        order = len(start_state)  # determine nth order of markov_chain
        prev_tuple = start_state[1:order]  # save all but the first word in tuple
        current_word = get_next_word(start_state, markov_model)  # get word after start state
        while current_word != "*E*":  # stop loop if we reach end state
            # determine tuple to enter into get_next_word (all but the first word + new word) - should update as it loops
            next_tuple = prev_tuple + (current_word,)
            current_word = get_next_word(next_tuple, markov_model)  # update current_word
            prev_tuple = next_tuple[1:order]  # update prev_tuple
            sentence += (" " + current_word)
        
    else:  # 1st order markov_chain
        sentence = start_state
        while current_word != "*E*":
            current_word = get_next_word(current_word, markov_model)
            sentence += (" " + current_word)
    
    
    sentence = sentence.rstrip("*E*")    
    return sentence

print(generate_random_text(markov_model))
```

------------------------------------------------------------------------

## All the Fish

Up till now, you have only been working with a line or two of the Dr. Seuss' *One Fish, Two Fish*. Now, I want you to build a model using the whole book and try different orders of Markov models.

```{python}
# Now just add some more training data to the markov model. You can find it under data/one_fish_two_fish.txt

markov_model = dict()
# Read in the whole book
with open("/courses/BINF6250.202610/students/fitzgerald.chr/Projects/BINF6250F25/projects/project02/one_fish_two_fish.txt", 'r') as txt_file:

    for line in txt_file:
        build_markov_model(markov_model, line, 1)
    return markov_model

print (generate_random_text(markov_model,seed=7))
```

------------------------------------------------------------------------

## Shakespeare

Now, let's play around with some Shakespeare.

```{python} 
# An example of a more complex text that we can use to generate more complex output 
sonet_markov_model = dict() 
file = open("/courses/BINF6250.202610/students/fitzgerald.chr/Projects/BINF6250F25/projects/project02/sonnets.txt", "r") 
sonet = "" 
for line in file: 
    line = line.strip() 
    if line == "":  # Empty line so build model 
        sonet_markov_model = build_markov_model(sonet_markov_model, sonet, order=2) 
        sonet = "" 
    else: 
        sonet = sonet + ' ' + line

print (generate_random_text(sonet_markov_model,seed=7))
